### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by warmonipa** [Sylverant/ship_server#1]
@ljsebald 

when i compile ship_server encounter error(centos7),
i run the following command:  
**touch config.rpath 
autoreconf --install
CFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib" ./configure --disable-ipv6
make**

**error info:**
epbase=`echo src/ship.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DPACKAGE_NAME=\"ship_server\" -DPACKAGE_TARNAME=\"ship_server\" -DPACKAGE_VERSION=\"0.1.0\" -DPACKAGE_STRING=\"ship_server\ 0.1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"ship_server\" -DVERSION=\"0.1.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBSYLVERANT=1 -DHAVE_LIBMINI18N=1 -DHAVE_LIBPSOARCHIVE=1 -DICONV_CONST= -DHAVE_PTHREAD=1 -DHAVE_ARPA_INET_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_NETDB_H=1 -DHAVE_NETINET_IN_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_SOCKET_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DSIZEOF_VOID_P=0 -DSIZEOF_INT=0 -DSIZEOF_LONG_INT=0 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=0 -Dmalloc=rpl_malloc -DHAVE_STDLIB_H=1 -DHAVE_REALLOC=0 -Drealloc=rpl_realloc -DHAVE_GETHOSTNAME=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_INET_NTOA=1 -DHAVE_MEMMOVE=1 -DHAVE_MEMSET=1 -DHAVE_SELECT=1 -DHAVE_SOCKET=1 -DHAVE_STRTOUL=1 -I.    -pthread -I/usr/local/include -I/usr/include/libxml2   -I/usr/include/p11-kit-1   -Wall -DGIT_BUILD="\"`git log --oneline | wc -l | tr -d \'[:space:]\'`\"" -DGIT_CHANGESET="\"`git show -s --pretty=format:%h`\"" -MT src/ship.o -MD -MP -MF $depbase.Tpo -c -o src/ship.o src/ship.c &&\
mv -f $depbase.Tpo $depbase.Po
src/ship.c: In function ‘ship_server_start’:
src/ship.c:668:21: error: ‘sylverant_ship_t’ has no member named ‘limits_count’
     for(i = 0; i < s->limits_count; ++i) {
                     ^
src/ship.c:671:13: error: ‘sylverant_ship_t’ has no member named ‘limits’
         if(s->limits[i].name && (!strcmp(s->limits[i].name, "default") ||
             ^
src/ship.c:671:43: error: ‘sylverant_ship_t’ has no member named ‘limits’
         if(s->limits[i].name && (!strcmp(s->limits[i].name, "default") ||
                                           ^
src/ship.c:672:43: error: ‘sylverant_ship_t’ has no member named ‘limits’
                                  !strcmp(s->limits[i].name, "list"))) {
                                           ^
src/ship.c:674:29: error: ‘sylverant_ship_t’ has no member named ‘limits’
                   s->name, s->limits[i].name);
                             ^
src/ship.c:678:56: error: ‘sylverant_ship_t’ has no member named ‘limits’
         debug(DBG_LOG, "%s:     Name: %s\n", s->name, s->limits[i].name);
                                                        ^
src/ship.c:680:35: error: ‘sylverant_ship_t’ has no member named ‘limits’
         if(sylverant_read_limits(s->limits[i].filename, &l)) {
                                   ^
src/ship.c:682:29: error: ‘sylverant_ship_t’ has no member named ‘limits’
                   s->name, s->limits[i].name, s->limits[i].filename);
                             ^
src/ship.c:682:48: error: ‘sylverant_ship_t’ has no member named ‘limits’
                   s->name, s->limits[i].name, s->limits[i].filename);
                                                ^
src/ship.c:694:13: error: ‘sylverant_ship_t’ has no member named ‘limits’
         if(s->limits[i].name) {
             ^
src/ship.c:695:38: error: ‘sylverant_ship_t’ has no member named ‘limits’
             if(!(ent->name = strdup(s->limits[i].name))) {
                                      ^
src/ship.c:709:13: error: ‘sylverant_ship_t’ has no member named ‘limits’
         if(s->limits[i].enforce)
             ^
src/ship.c: In function ‘ship_check_cfg’:
src/ship.c:870:21: error: ‘sylverant_ship_t’ has no member named ‘limits_count’
     for(i = 0; i < s->limits_count; ++i) {
                     ^
src/ship.c:874:13: error: ‘sylverant_ship_t’ has no member named ‘limits’
         if(s->limits[i].name && (!strcmp(s->limits[i].name, "default") ||
             ^
src/ship.c:874:43: error: ‘sylverant_ship_t’ has no member named ‘limits’
         if(s->limits[i].name && (!strcmp(s->limits[i].name, "default") ||
                                           ^
src/ship.c:875:43: error: ‘sylverant_ship_t’ has no member named ‘limits’
                                  !strcmp(s->limits[i].name, "list"))) {
                                           ^
src/ship.c:877:20: error: ‘sylverant_ship_t’ has no member named ‘limits’
                   s->limits[i].name);
                    ^
src/ship.c:880:56: error: ‘sylverant_ship_t’ has no member named ‘limits’
         debug(DBG_LOG, "%s:     Name: %s\n", s->name, s->limits[i].name);
                                                        ^
src/ship.c:882:35: error: ‘sylverant_ship_t’ has no member named ‘limits’
         if(sylverant_read_limits(s->limits[i].filename, &l)) {
                                   ^
src/ship.c:884:29: error: ‘sylverant_ship_t’ has no member named ‘limits’
                   s->name, s->limits[i].name, s->limits[i].filename);
                             ^
src/ship.c:884:48: error: ‘sylverant_ship_t’ has no member named ‘limits’
                   s->name, s->limits[i].name, s->limits[i].filename);
                                                ^
src/ship.c:893:13: error: ‘sylverant_ship_t’ has no member named ‘limits’
         if(s->limits[i].name) {
             ^
src/ship.c:894:38: error: ‘sylverant_ship_t’ has no member named ‘limits’
             if(!(ent->name = strdup(s->limits[i].name))) {
                                      ^
src/ship.c:906:13: error: ‘sylverant_ship_t’ has no member named ‘limits’
         if(s->limits[i].enforce)
             ^
make[1]: *** [src/ship.o] Error 1
make[1]: Leaving directory `/home/sylverant/Desktop/pso/ship_server'
make: *** [all-recursive] Error 1

**Comment by ljsebald** [comment]
You appear to be compiling against an out-of-date version of libsylverant. Try pulling and compiling it again.

Also, keep in mind that the official repositories for Sylverant are hosted on Sourceforge, not here. These are simply mirrors of what is on Sourceforge.

**Comment by warmonipa** [comment]
ok, thx
