### ISSUE TITLE
No release/repack or ressources available ?

### ISSUE THREAD

**Issue by Test045** [Sylverant/ship_server#2]
Hi. I have no issue compiling the whole project. I'd like to contribute to Sylverant's code, as I'm back at PSO, and have started my own server project in c++ (supporting gamecube only for now) and Sylverant has been very insipiring in terms of coding/understanding the pso protocol.

 Yet, I have no clue how to run the server as it seems a lot of resources are missing, and it seems there are no guides about it beside configuring the dtd/xml tied to the server configuratiin, which also points to ressources not available in this repo afaik.

Would it be possible to host the ressources somewhere, or simply do just a repack so i can run a server on m LAN and test fixes / understand how things work / get inspired ?

**Comment by ljsebald** [comment]
Unfortunately, most of the resources that aren't around (or aren't documented on the main project over on sourceforge -- https://sourceforge.net/p/sylverant/wiki/browse_pages/) are stuff directly from Sega's server (or from the game client's data files), which can't really be distributed without permission from Sega.

That said, some of the documentation is a bit out of date (I hate writing documentation and I'm pretty much a one-man-band here), but most of it is still usable...

**Comment by Test045** [comment]
Thank you for your answer. Guess I'll just keep working on my own GC project server then
