### ISSUE TITLE
[ship_server, login_server] configure.ac configuration update (cross-compile, autotools)

### ISSUE THREAD

**Issue by Diskmaster** [Sylverant/ship_server#3]
Issue: On Gentoo Linux and possibly other linux distributions, there's an issue with how autotools checks for malloc, which results in undefined rpl_malloc errors with the current configuration. Essentially remove or comment out AC_FUNC_MALLOC/REALLOC and add the equivalents to AC_CHECK_FUNCS, as the related tests don't run in a cross-compile environment.

Apparently https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Particular-Functions.html#AC_FUNC_MALLOC is a useful reference, here.

```
diff --git a/configure.ac b/configure.ac
index a05e80b..a312e9f 100644
--- a/configure.ac
+++ b/configure.ac
@@ -64,9 +64,9 @@ AC_TYPE_UINT8_T
 AC_C_BIGENDIAN

 # Checks for library functions.
-AC_FUNC_MALLOC
-AC_FUNC_REALLOC
-AC_CHECK_FUNCS([gethostname gettimeofday inet_ntoa memmove memset select socket strtoul])
+#AC_FUNC_MALLOC
+#AC_FUNC_REALLOC
+AC_CHECK_FUNCS([malloc realloc gethostname gettimeofday inet_ntoa memmove memset select socket strtoul])

 ADD_CFLAGS([-Wall])
```

**Comment by ljsebald** [comment]
Sorry for the late update, but this is resolved in ship_server now.
